### ISSUE TITLE
Когда создаю оффер, по умолчанию в поле template стоит шаблон index, который не работает

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#13]
![2014-11-24 21 56 49](https://cloud.githubusercontent.com/assets/9354450/5172994/ef7987d6-7424-11e4-9237-15ac0de4fcd4.png)
![2014-11-24 21 57 30](https://cloud.githubusercontent.com/assets/9354450/5173002/037ec8fe-7425-11e4-9805-5de1c375734a.png)

**Comment by schaman** [comment]
fixed
