### ISSUE TITLE
Ссылка на подтверждение рассылки не работает

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#14]
При регистрации на вебинар (product 1) мне на мыло приходит подтверждение подписки (shot 2)

![2014-11-26 18 47 30](https://cloud.githubusercontent.com/assets/9354450/5206011/bc0c4f72-759c-11e4-8d89-8d3c3a8ef524.png)

Нажимаю на ссылку - выскакивает сообщение об ошибке

![2014-11-26 18 48 56](https://cloud.githubusercontent.com/assets/9354450/5206021/e781de06-759c-11e4-8510-1c15123ff2d7.png)

Не пойму, где ошибка в шотах и мейлинглисте - вроде все правильно

**Comment by schaman** [comment]
fixed
