### ISSUE TITLE
Заказ upsell'а не работает

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#15]
Заказал вебинар (product 1), перехожу на страницу "Спасибо + upsell" (shot 1)

![2014-11-26 19 23 32](https://cloud.githubusercontent.com/assets/9354450/5206471/077256b4-75a2-11e4-9282-d37b369a604f.png)

Нажимаю "Заказать" и не работает

![2014-11-26 19 23 20](https://cloud.githubusercontent.com/assets/9354450/5206500/3d9ad5ae-75a2-11e4-97da-e675a971cc03.png)

**Comment by schaman** [comment]
Order post error 400 Product 4 not found

означает

Ошибка сохранения заказа
400 = Неправильный запрос
Продукт с ID=4 не найден

Продукта такого нет.
