### ISSUE TITLE
Улучшения документации

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#20]
Я сам менять не стал, но нашел неточность.

В вики тут: https://github.com/schaman/yo/wiki/HOWTO:-Create-appointment-flow написано вот здесь

![2014-11-27 11 35 42](https://cloud.githubusercontent.com/assets/9354450/5215642/b410d7ce-7629-11e4-9a15-a1b7143f683f.png)

Что надо создать flow на сайте prorealnost.icoach.io

![2014-11-27 11 35 43](https://cloud.githubusercontent.com/assets/9354450/5215649/c589d154-7629-11e4-8571-597c3b8d3db3.png)

А я flow создаю на сайте money.prorealnost.io

Допиши, пожалуйста, в документацию, для каких офферов на каких сайтах надо создавать потоки. Спасибо!

**Comment by schaman** [comment]
Это просто пример
