### ISSUE TITLE
Проверка на дурака выдает ошибку

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#21]
Если случайно нажать на Enter тут

![2014-11-27 11 41 23](https://cloud.githubusercontent.com/assets/9354450/5215701/67f6233e-762a-11e4-9dc5-9c62a2fd6e0e.png)

То все ломаеццо.

![2014-11-27 11 41 18](https://cloud.githubusercontent.com/assets/9354450/5215703/77b77c32-762a-11e4-92d3-c1f5d4cbc26a.png)

**Comment by schaman** [comment]
fixed
