### ISSUE TITLE
Не работает главная страница money.prorealnost

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#25]
Видимо, опять проблемы со шрифтом

![novy_tochechny_risunok](https://cloud.githubusercontent.com/assets/9354450/5239849/bf836bc0-78f0-11e4-96a8-5568f52750e6.JPG)

**Comment by schaman** [comment]
Поменяй тему theme-first, там есть css, где написано font-family: Lato, Helvetica,... во многих разных местах файла

Надо убрать "Lato", чтобы было просто  font-family: Helvetica,...

**Comment by kirilldudinsky** [comment]
Я не понял. 

> Там есть css

Там, это видимо тут:

![2014-12-02 16 25 53](https://cloud.githubusercontent.com/assets/9354450/5265046/ef362380-7a3f-11e4-9d66-72b2a0340c00.png)

В файле flat-ui.css везде написано font-family: Lato. Helvetica нигде нет. Насколько я понял, надо поменять Lato на Helvetica. Но я не хотел бы без Тебя ничего менять сам в css.

**Comment by schaman** [comment]
У меня всё работает. Что у тебя написано в консоли javascript?

**Comment by kirilldudinsky** [comment]
у меня тоже все работает. 

и в консоли отображается вот что:

![2014-12-02 20 31 50](https://cloud.githubusercontent.com/assets/9354450/5269367/4c422a8e-7a62-11e4-8388-caaefd4e0d5b.png)

это люди присылали. и она все еще не работает - шрифты не отображаются. минут через 10 я узнаю, что у человека в консоли отображается

**Comment by schaman** [comment]
заменил шрифт на более безопасный open sans
