### ISSUE TITLE
Сделать метрики для отдела траффика

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#26]
Описание метрик для money.prorealnost.com (дополнения и уточнения пиши в комментах):
1. Количество уникальных посетителей по каждому источнику траффика - человек перешел по ссылке с меткой
2. Количество регистраций по каждому источнику траффика - человек, перешедший по ссылке с меткой, зарегистрировался
3. Количество участников вебинара по каждому источнику траффика - сколько людей, зарегистрировавшихся из данного источника траффика пришли на вебинар (думаю, это можно узнать, подсчитав, сколько людей нажали на ссылку на страницу трансляции со спец. меткой)
4. Количество и статус (новые или уже зарегистрировавшиеся) участников вебинара, заказавших продукт по каждому источнику траффика

**Comment by schaman** [comment]
Готово.

Документация тут: https://github.com/schaman/yo/wiki/Metric

Пример тут: http://money.prorealnost.com/admin/src/metric/1
