### ISSUE TITLE
Ошибка 500 - что-то сломалось

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#28]
[Делаю заказ](http://money.prorealnost.com/offer/kak-zarabotat-60000-rublei-za-mesyac)

![2014-12-14 18 07 46](https://cloud.githubusercontent.com/assets/9354450/5428257/4ed9be20-83bc-11e4-8f36-9a1d58244a6b.png)

Выдается ошибка 500

![2014-12-14 18 07 35](https://cloud.githubusercontent.com/assets/9354450/5428258/575dd694-83bc-11e4-95ef-8d9a447c155a.png)

**Comment by schaman** [comment]
fixed
