### ISSUE TITLE
А правильно ли считаются метрики?

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#29]
Речь идет про метрики [тут](http://money.prorealnost.com/admin/src/metric/2)

Зарегистрировалось без источника 67 из 30 посетителей (что уже само по себе странно)

![2014-12-15 22 10 48](https://cloud.githubusercontent.com/assets/9354450/5444048/78abf524-84a7-11e4-83ce-563a118fdfb8.png)

И всего регистраций 125

![2014-12-15 22 10 59](https://cloud.githubusercontent.com/assets/9354450/5444054/853f68ac-84a7-11e4-8e9c-fa553551d6ce.png)

А заказов продукта всего 64 [тут](http://ic.icoach.io/admin/product/8).

![2014-12-15 22 11 18](https://cloud.githubusercontent.com/assets/9354450/5444067/adc68cf6-84a7-11e4-8152-772b68a01237.png)

Числа 125 и 64 между собой не совпадают. А по идее должны совпадать. Почему не совпадают?

**Comment by schaman** [comment]
fixed

Были посчитаны заходы роботов.

Так как робот пытается получить страницу shot/31 не через заполнение формы, а напрямую, он получает ошибку. Поэтому решает попробовать ещё разок. И так до 150 раз в день от особо упорных (Яндекс).

1) Роботам запрещено ходить внутрь шотов
2) Засчитываются только успешные заходы (statuscode < 400)
