### ISSUE TITLE
Некорректно работает вставка видео в шот страницы с вещанием

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#31]
Вот [тут](http://money.prorealnost.com/shot/80)

flow [тут](http://money.prorealnost.com/admin/flow/shot/80)

**Comment by schaman** [comment]
Там надо было не всю ссылку вставлять, а только ID потока поменять.

Не так: https://www.youtube.com/watch?v=bAvkllY5bpE

А вот так: http://www.youtube.com/embed/bAvkllY5bpE

Тогда работает
