### ISSUE TITLE
Не работает шот переадресации на страницу оплаты - не могу понять, что не так

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#32]
[флоу](http://money.prorealnost.com/admin/flow/33)

[шот 113](http://money.prorealnost.com/shot/113) работает

![2015-03-02 1 04 20](https://cloud.githubusercontent.com/assets/9354450/6433782/2ad0ecee-c078-11e4-9767-c714523e152c.png)

И следующий шот - 114 - не работает

![2015-03-02 1 05 32](https://cloud.githubusercontent.com/assets/9354450/6433785/428a4132-c078-11e4-9d8c-f7586f875da5.png)

Что я делаю не так?

**Comment by schaman** [comment]
не rom, а from
