### ISSUE TITLE
Как Улучшить секцию О тренере

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#33]
На новой главной странице ПроРеальности 

есть секция 

о тренере

![2015-03-02 4 55 21](https://cloud.githubusercontent.com/assets/9354450/6435198/66b8ff38-c098-11e4-98c2-58bbaae2bf25.png)

Справа внизу добавить картинки телеканалов, как вот тут

![2015-03-02 4 56 22](https://cloud.githubusercontent.com/assets/9354450/6435202/7e420fa0-c098-11e4-8473-ae3f7203471e.png)

Под фразой Вдохновил 2500 человек добавить описание со старого айкоуча

Николай Воробьёв — Автор 5 книг и 15 тренингов об отношениях, мотивации, уверенности, бизнесе, продажах и личной эффективности 

Провёл тренинги более чем в 20 городах России и Европы 

Ведущий и тренер в 4 телевизионных и радио шоу об отношениях и личной эффективности 

Владелец 4 компаний Тренер и коуч с 12-летним опытом 

В настоящее время проводит тренинги личной эффективности и персональный коучинг, готовит тренеров

Ведущий радио- и телевизионных проектов 
2006 Телевизионное шоу «Правила съёма», ТНТ, Россия — эксперт по соблазнению 
2010 Телевизионное реалити-шоу «Pro Любoff», 1+1, Украина — тренер для женщин
2011-2013 Радиошоу «Школа Соблазна», podster.ru — соавтор и ведущий 
2012 Реалити-шоу «ПроРеальность», podster.ru — автор и ведущий 
2013 Медиашкола Live, Санкт-Петербург — мотивационный тренер

**Comment by schaman** [comment]
хуйня получается
