### ISSUE TITLE
Комментарии на странице вещания не работают

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/yo#35]
[Вот в этом шоте](http://prolubov.com/shot/41)

![2015-04-12 20 30 37](https://cloud.githubusercontent.com/assets/9354450/7106937/f8648b98-e152-11e4-998b-c5f43d3902f1.png)

**Comment by schaman** [comment]
Комментарии привязаны к домену prorealnost.com, а вещание идёт с prolubov.com.

Сделай переадресацию на prolubov.prorealnost.com, как и в прошлый раз.
